version: "3.3"
services:
  asterisk:
    container_name: asterisk
    image: garage11/asterisk:latest
    depends_on:
      - coturn
      - postgres
      - nginx
    network_mode: host
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/config.ini:/root/asterisk/contrib/ast-db-manage/config.ini
      - ./asterisk/odbcinst.ini:/etc/odbcinst.ini
      - ./asterisk/odbc.ini:/etc/odbc.ini
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: asterisk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ca11ftw
    image: postgres:latest
    network_mode: host
    user: ${CURRENT_UID:-999:985}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build:/usr/share/nginx/html/build
      - ../packages:/usr/share/nginx/html/packages
  coturn:
    container_name: coturn
    image: instrumentisto/coturn
    network_mode: host
    restart: always
volumes:
  postgres:
