services:
  asterisk:
    container_name: ca11_asterisk
    image: ca11/asterisk:latest
    volumes:
      - ./asterisk/config:/etc/asterisk
      - ./asterisk/config.ini:/root/asterisk/contrib/ast-db-manage/config.ini
      - ./asterisk/odbcinst.ini:/etc/odbcinst.ini
      - ./asterisk/odbc.ini:/etc/odbc.ini

  coturn:
    container_name: ca11_coturn
    image: instrumentisto/coturn

  postgresql:
    container_name: ca11_postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-asterisk}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ca11ftw}
    image: postgres:latest
    volumes:
      - postgresql:/var/lib/postgresql/data

  nginx:
    container_name: ca11_nginx
    image: nginx
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build:/usr/share/nginx/html

  sfu:
    container_name: ca11_sfu
    image: ca11/sfu:latest
    volumes:
      - ./sfu/config.toml:/ca11/config.toml

version: "3.8"
volumes:
  postgresql:
